# Generated by Django 5.0 on 2024-01-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_customer_book_remove_customer_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
