# Generated by Django 5.0 on 2024-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_customer_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomerNameHistory',
        ),
    ]
