# Generated by Django 5.0 on 2024-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
